"""Add image column to hero

Revision ID: 678c7ec2f168
Revises: 5f36d0501eb3
Create Date: 2023-10-13 00:08:57.699029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '678c7ec2f168'
down_revision = '5f36d0501eb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
